name: pytest

on:
  pull_request:
    paths:
      - "lambda/**"
  push:
    paths:
      - "lambda/**"
  workflow_dispatch:

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: Install dependencies in virtualenv and run unit tests
        working-directory: lambda
        run: |
          python -m venv env
          source env/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt
          pytest
          deactivate
